### ISSUE TITLE
Assembling the test data does not generate an assembly

### ISSUE THREAD

**Issue by methylome** [vpc-ccg/haslr#37]
Conda and make version do not generate an assembly for the E. coli dataset.

>ll ecoli
total 224M
drwxr-xr-x 2 cjh info 4.0K Jul 25 19:00 asm_contigs_k49_a3_lr25x_b500_s3_sim0.85
-rw-r--r-- 1 cjh info 2.2K Jul 25 19:00 asm_contigs_k49_a3_lr25x_b500_s3_sim0.85.err
-rw-r--r-- 1 cjh info    0 Jul 25 19:00 asm_contigs_k49_a3_lr25x_b500_s3_sim0.85.out
-rw-r--r-- 1 cjh info 111M Jul 25 16:32 lr25x.fasta
-rw-r--r-- 1 cjh info  736 Jul 25 19:00 map_contigs_k49_a3_lr25x.log
-rw-r--r-- 1 cjh info    0 Jul 25 19:00 map_contigs_k49_a3_lr25x.paf
-rw-r--r-- 1 cjh info   86 Jul 25 16:32 sr.fofn
-rw-r--r-- 1 cjh info    0 Jul 25 19:00 sr_k49_a3.contigs.nooverlap.250.fa
-rw-r--r-- 1 cjh info    0 Jul 25 19:00 sr_k49_a3.contigs.nooverlap.fa
-rw-r--r-- 1 cjh info 114M Jul 25 19:00 sr_k49_a3.h5
-rw-r--r-- 1 cjh info  37K Jul 25 19:00 sr_k49_a3.log
-rw-r--r-- 1 cjh info    0 Jul 25 17:06 sr_k49_a3.unitigs.fa.doubledKmers.4
-rw-r--r-- 1 cjh info    0 Jul 25 17:06 sr_k49_a3.unitigs.fa.doubledKmers.5
-rw-r--r-- 1 cjh info    0 Jul 25 17:06 sr_k49_a3.unitigs.fa.doubledKmers.6
-rw-r--r-- 1 cjh info    0 Jul 25 17:06 sr_k49_a3.unitigs.fa.doubledKmers.7

>ll ecoli/asm_contigs_k49_a3_lr25x_b500_s3_sim0.85
total 28M
-rw-r--r-- 1 cjh info   0 Jul 25 19:00 asm.final.ann
-rw-r--r-- 1 cjh info   0 Jul 25 19:00 asm.final.fa
-rw-r--r-- 1 cjh info   0 Jul 25 19:00 backbone.01.init.gfa
-rw-r--r-- 1 cjh info   0 Jul 25 19:00 backbone.01.init.stat
-rw-r--r-- 1 cjh info   0 Jul 25 19:00 backbone.02.weakEdge.gfa
-rw-r--r-- 1 cjh info  42 Jul 25 19:00 backbone.02.weakEdge.stat
-rw-r--r-- 1 cjh info   0 Jul 25 19:00 backbone.03.tip.gfa
-rw-r--r-- 1 cjh info   0 Jul 25 19:00 backbone.03.tip.log
-rw-r--r-- 1 cjh info  42 Jul 25 19:00 backbone.03.tip.stat
-rw-r--r-- 1 cjh info   0 Jul 25 19:00 backbone.04.simplebubble.gfa
-rw-r--r-- 1 cjh info   0 Jul 25 19:00 backbone.04.simplebubble.log
-rw-r--r-- 1 cjh info  42 Jul 25 19:00 backbone.04.simplebubble.stat
-rw-r--r-- 1 cjh info   0 Jul 25 19:00 backbone.05.superbubble.gfa
-rw-r--r-- 1 cjh info   0 Jul 25 19:00 backbone.05.superbubble.log
-rw-r--r-- 1 cjh info  42 Jul 25 19:00 backbone.05.superbubble.stat
-rw-r--r-- 1 cjh info   0 Jul 25 19:00 backbone.06.smallbubble.gfa
-rw-r--r-- 1 cjh info   0 Jul 25 19:00 backbone.06.smallbubble.log
-rw-r--r-- 1 cjh info  42 Jul 25 19:00 backbone.06.smallbubble.stat
-rw-r--r-- 1 cjh info   0 Jul 25 19:00 backbone.branching.log
-rw-r--r-- 1 cjh info 44K Jul 25 19:00 compact_uniq.txt
-rw-r--r-- 1 cjh info  16 Jul 25 19:00 index.contig
-rw-r--r-- 1 cjh info 28M Jul 25 19:00 index.longread
-rw-r--r-- 1 cjh info   0 Jul 25 19:00 log_asmfinal.txt

>cat ecoli/asm_contigs_k49_a3_lr25x_b500_s3_sim0.85.err
[NOTE] number of threads: 8

[NOTE] loading contig sequences...
       processing file: ecoli/sr_k49_a3.contigs.nooverlap.fa... Done in 0.00 CPU seconds (0.00 real seconds)
       loaded 0 contigs
       elapsed time 0.00 CPU seconds (0.00 real seconds)

[NOTE] calculating kmer frequency of unique contigs
       mean: -nan
       elapsed time 0.00 CPU seconds (0.00 real seconds)

[NOTE] loading long read sequences...
       processing file: ecoli/lr25x.fasta... Done in 0.40 CPU seconds (0.40 real seconds)
       loaded 6453 long reads
       elapsed time 0.41 CPU seconds (0.41 real seconds)

[NOTE] loading alignment between contigs and long reads...
       processing file: ecoli/map_contigs_k49_a3_lr25x.paf... Done in 0.00 CPU seconds (0.00 real seconds)
       loaded 0 alignments
       elapsed time 0.44 CPU seconds (0.45 real seconds)

[NOTE] fixing overlapping alignments...
       elapsed time 0.44 CPU seconds (0.45 real seconds)

[NOTE] building compact long reads...
       elapsed time 0.45 CPU seconds (0.45 real seconds)

[NOTE] building the backbone graph...
       elapsed time 0.45 CPU seconds (0.45 real seconds)

[NOTE] cleaning weak edges...
       removed 0 edges
       elapsed time 0.45 CPU seconds (0.45 real seconds)

[NOTE] cleaning tips...
       removed 0 tips
       elapsed time 0.45 CPU seconds (0.46 real seconds)

[NOTE] cleaning simple bubbles...
       removed 0 simple bubbles
       elapsed time 0.45 CPU seconds (0.46 real seconds)

[NOTE] cleaning super bubbles...
       removed 0 super bubbles
       elapsed time 0.45 CPU seconds (0.46 real seconds)

[NOTE] cleaning small bubbles...
       removed 0 small bubbles
       elapsed time 0.45 CPU seconds (0.46 real seconds)

[NOTE] calculating long read coordinates between anchors...
       elapsed time 0.45 CPU seconds (0.46 real seconds)

[NOTE] calling consensus sequence between anchors...
       elapsed time 0.45 CPU seconds (0.46 real seconds)

[NOTE] generating the assembly from the cleaned backbone graph...
       elapsed time 0.45 CPU seconds (0.46 real seconds)

[NOTE] cleaning up the memory!
[NOTE] elapsed time 0.45 CPU seconds (0.47 real seconds)

*** BYE ***

**Comment by methylome** [comment]
I downloaded v0.8a1 which did not work.
Solved as suggested in https://github.com/vpc-ccg/haslr/issues/18#issuecomment-841536244

**Comment by salvatierra8** [comment]
hope you still remember how to use this... i'm trying to fix this by using ISonets's solution. So by

    Installing from source? --- If yes... check
    by using: conda install -c bioconda haslr? --- if yes... check
    by "all" i understand all the haslr bin folder created by step 1 --- if yes... check
    No profit :(
