### ISSUE TITLE
Using CCS/HiFi PacBio reads

### ISSUE THREAD

**Issue by mbhall88** [vpc-ccg/haslr#6]
Is there anything "wrong" with me using CCS reads for the long reads? i.e. is there some kind of inferred error rate attached to the long reads parameter that will mess this up? (CCS reads have a very low error rate compared to raw ont/pacbio)

**Comment by haghshenas** [comment]
Hi Michael,

There is nothing wrong with using HiFi long reads. But we might get too many alignments when aligning short read contigs to long reads using either `-x pacbio` or `-x nanopore`.
I need to make another option for these reads.

**Comment by haghshenas** [comment]
I added the experimental option `-x corrected`. It employs minimap2 with a larger k-mer size compared to `-x pacbio` and `-x nanopore`.

**Comment by haghshenas** [comment]
Remember that before I update the bioconda recipe, in order to get the latest changes, you need to build HASLR from source (check [here](https://github.com/vpc-ccg/haslr/#building)) rather than using the bioconda version. 
The bioconda recipe will be updated after releasing a new tag.

**Comment by mbhall88** [comment]
When you say `-x pacbio` are you referring to minimap2 params? If so, there is a preset for CCS reads `-x asm20`.

**Comment by haghshenas** [comment]
Not exactly. It doesn't pass the same parameter to minimap2.

**Comment by mbhall88** [comment]
For my own interest, how come you don't use the presets for the different technologies?
