### ISSUE TITLE
Set coverage to use all

### ISSUE THREAD

**Issue by mbhall88** [vpc-ccg/haslr#7]
Is it possible to specify that you don't want to subsample to a certain coverage? 

I can obviously set `--cov-lr`  to something huge, but is there something like setting it to 0 to tell it to just use all?

**Comment by haghshenas** [comment]
So far there is no option to do that.
I'll work on this to add an option to make things more convenient.

**Comment by haghshenas** [comment]
I implemented your suggestion. 
The latest commit should use all long reads when `--cov-lr` is set to 0.

Thanks for the suggestion.

**Comment by conchoecia** [comment]
Thanks for implementing that, and for writing the software, @haghshenas. Just came by to point out that this change is not yet on the conda version. I was able to get `--cov-lr 0` to work when I installed from github though.
